-- Idempotent seed: NOT EXISTS avoids duplicate rows when entity_id IS NULL
-- (UNIQUE(name, entity_id) does not treat NULL entity_id as equal in PostgreSQL).

INSERT INTO roles (name, display_name, level, entity_type, is_system, permissions)
SELECT v.name, v.display_name, v.level, v.entity_type, v.is_system, v.permissions::jsonb
FROM (VALUES
  ('support',       'Support (ThinkSys)',  1000, 'system',   true, '{"actions":["visitor:create","visitor:read","visitor:update","visitor:delete","visit_request:create","visit_request:read","visit_request:approve","visit_request:reject","visit_request:checkin","visit_request:checkout","visit_request:more_info","qr:scan","qr:generate","qr:revoke","user:create","user:read","user:update","user:delete","user:impersonate","role:create","role:read","role:update","role:delete","role:assign","report:view","report:export","settings:read","settings:update","entity:create","entity:read","entity:update","entity:delete","audit_log:read","audit_log:export","watchlist:create","watchlist:read","watchlist:update","watchlist:delete","notification:configure","notification:send"],"not_actions":[]}'),
  ('tower',         'Tower',               800,  'tower',    true, '{"actions":["entity:create","entity:read","entity:update","entity:delete","user:create","user:read","user:update","role:create","role:read","role:update","role:delete","role:assign","report:view","report:export","settings:read","settings:update","visitor:read","visit_request:read","audit_log:read","image:upload_self","image:upload_child","employee:csv_upload_self","employee:csv_upload_child"],"not_actions":[]}'),
  ('organization',  'Organization',        800,  'organization', true, '{"actions":["entity:create","entity:read","entity:update","entity:delete","user:create","user:read","user:update","role:create","role:read","role:update","role:delete","role:assign","report:view","report:export","settings:read","settings:update","visitor:read","visit_request:read","audit_log:read"],"not_actions":[]}'),
  ('company',       'Company',             600,  'company',  true, '{"actions":["entity:read","entity:update","user:create","user:read","user:update","user:delete","role:create","role:read","role:assign","report:view","report:export","settings:read","settings:update","visitor:read","visit_request:read","audit_log:read","notification:configure","image:upload_self","image:upload_child","employee:csv_upload_self","employee:csv_upload_child"],"not_actions":[]}'),
  ('location',      'Location',            600,  'location', true, '{"actions":["entity:read","entity:update","user:create","user:read","user:update","user:delete","role:create","role:read","role:assign","report:view","report:export","settings:read","settings:update","visitor:read","visit_request:read","audit_log:read","notification:configure","image:upload_self","image:upload_child","employee:csv_upload_self","employee:csv_upload_child"],"not_actions":[]}'),
  ('admin',         'Admin',               400,  'any',      true, '{"actions":["user:create","user:read","user:update","role:create","role:read","role:assign","report:view","report:export","settings:read","settings:update","visitor:read","visit_request:read","visit_request:approve","visit_request:reject","visit_request:more_info","audit_log:read","notification:configure"],"not_actions":[]}'),
  ('front_desk',    'Front Desk',          200,  'any',      true, '{"actions":["visitor:create","visitor:read","visitor:update","visit_request:create","visit_request:read","visit_request:approve","visit_request:reject","visit_request:more_info","qr:generate","user:read","report:view","notification:send"],"not_actions":[]}'),
  ('gate',          'Gate Receptionist',   100,  'any',      true, '{"actions":["visitor:create","visitor:read","visit_request:create","visit_request:read","visit_request:checkin","visit_request:checkout","qr:scan","qr:generate"],"not_actions":[]}')
) AS v(name, display_name, level, entity_type, is_system, permissions)
WHERE NOT EXISTS (
  SELECT 1 FROM roles r WHERE r.name = v.name AND r.entity_id IS NULL
);
